export interface HomepageSection {
  id: string;
  number: string;
  title: string;
  subtitle: string;
  description: string;
  range: [number, number]; // Normalized scroll progress range [start, end]
  accentColor: string;
  primaryCta?: { text: string; href: string; action?: string };
  secondaryCta?: { text: string; href: string };
  codeSnippet?: string;
}

export const HOMEPAGE_SECTIONS: HomepageSection[] = [
  {
    id: 'hero-universe',
    number: '01',
    title: 'Design CSS Visually.',
    subtitle: 'Build Without Limits.',
    description: 'Welcome to the CSS Studio Universe. Scroll to embark on a continuous 3D journey through modern visual layout engines, keyframe animations, component galaxies, and production code generation.',
    range: [0.0, 0.07],
    accentColor: '#3b82f6',
    primaryCta: { text: 'Start Designing', href: '/editor', action: 'create' },
    secondaryCta: { text: 'Explore Visual Builder', href: '/builder' },
    codeSnippet: `/* CSS STUDIO CORE ENGINE */\n.css-core {\n  display: universe;\n  transform-style: preserve-3d;\n  animation: orbit 20s infinite linear;\n}`,
  },
  {
    id: 'code-to-visual',
    number: '02',
    title: 'Write Less. See More.',
    subtitle: 'Code Physically Morphing Into UI',
    description: 'Watch raw CSS property declarations disassemble into energy particles and physically assemble into responsive, styled 3D user interface blocks.',
    range: [0.07, 0.14],
    accentColor: '#8b5cf6',
    primaryCta: { text: 'Try Live CSS Editor', href: '/editor' },
    codeSnippet: `.card {\n  display: flex;\n  border-radius: 24px;\n  box-shadow: 0 20px 40px rgba(59, 130, 246, 0.3);\n  backdrop-filter: blur(16px);\n}`,
  },
  {
    id: 'visual-builder',
    number: '03',
    title: 'Drag. Drop. Design.',
    subtitle: 'Build Real Websites Visually',
    description: 'A giant 3D browser viewport surrounded by floating building blocks—headings, buttons, containers, and images—snapping into position effortlessly.',
    range: [0.14, 0.21],
    accentColor: '#ec4899',
    primaryCta: { text: 'Launch Website Builder', href: '/builder' },
    codeSnippet: `<div className="visual-builder-root">\n  <Navbar layout="sticky" />\n  <HeroSection theme="3d-universe" />\n  <FeatureGrid columns={3} />\n</div>`,
  },
  {
    id: 'responsive-dimension',
    number: '04',
    title: 'Responsive by Design.',
    subtitle: 'One Canvas across All Breakpoints',
    description: 'Watch your layout dynamically fluidly adapt across Desktop, Laptop, Tablet, and Mobile 3D device rigs in real time.',
    range: [0.21, 0.28],
    accentColor: '#10b981',
    primaryCta: { text: 'Test Responsive Engine', href: '/builder' },
    codeSnippet: `@media (max-width: 768px) {\n  .grid-layout {\n    grid-template-columns: 1fr;\n    gap: 16px;\n  }\n}`,
  },
  {
    id: 'motion-lab',
    number: '05',
    title: 'Make Interfaces Move.',
    subtitle: 'Timeline & Keyframe Studio',
    description: 'Control spring physics, easing curves, dynamic rotation, and scaling across an interactive CSS animation timeline.',
    range: [0.28, 0.35],
    accentColor: '#f59e0b',
    primaryCta: { text: 'Open Keyframe Studio', href: '/editor' },
    codeSnippet: `@keyframes float {\n  0% { transform: translateY(40px) rotate(0deg); }\n  50% { transform: translateY(-20px) rotate(180deg); }\n  100% { transform: translateY(40px) rotate(360deg); }\n}`,
  },
  {
    id: 'flexbox-dimension',
    number: '06',
    title: 'Understand Layouts by Seeing Them.',
    subtitle: 'Interactive 3D Flexbox Axis',
    description: 'Toggle flex-direction, justify-content, align-items, and gap properties to see 3D blocks physically shift along glowing spatial vectors.',
    range: [0.35, 0.42],
    accentColor: '#06b6d4',
    primaryCta: { text: 'Try Flexbox Playground', href: '/flexbox' },
    codeSnippet: `.flex-container {\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n  gap: 24px;\n}`,
  },
  {
    id: 'grid-matrix',
    number: '07',
    title: 'The CSS Grid Matrix.',
    subtitle: 'Multi-Track 3D Spatial Layouts',
    description: 'Expand glowing 3D grid cells, customize grid-template-areas, auto-fit tracks, and span columns across a holographic 12-column grid space.',
    range: [0.42, 0.50],
    accentColor: '#a855f7',
    primaryCta: { text: 'Open Grid Playground', href: '/grid' },
    codeSnippet: `.grid-matrix {\n  display: grid;\n  grid-template-columns: repeat(12, 1fr);\n  gap: 20px;\n}`,
  },
  {
    id: 'component-galaxy',
    number: '08',
    title: 'Build Once. Reuse Everywhere.',
    subtitle: '3D UI Component Constellation',
    description: 'An orbiting galaxy of modular UI components—buttons, pricing cards, tooltips, navbars, and modals—ready to drop into your projects.',
    range: [0.50, 0.58],
    accentColor: '#3b82f6',
    primaryCta: { text: 'Explore Component Library', href: '/builder' },
    codeSnippet: `<Button variant="glass" shadow="glowing" radius="xl">\n  <Sparkles /> Launch Project\n</Button>`,
  },
  {
    id: 'website-assembly',
    number: '09',
    title: 'From Blank Canvas to Complete Website.',
    subtitle: 'Full 3D Page Assembly Sequence',
    description: 'Experience an entire high-converting web application assemble piece by piece right before your eyes inside a 3D environment.',
    range: [0.58, 0.66],
    accentColor: '#6366f1',
    primaryCta: { text: 'Build Your Site Now', href: '/builder' },
    codeSnippet: `/* PRODUCTION BUILD COMPLETE */\n.website-wrapper {\n  max-width: 1280px;\n  margin: 0 auto;\n  opacity: 1;\n}`,
  },
  {
    id: 'css-art-dimension',
    number: '10',
    title: 'CSS is More Than Layouts.',
    subtitle: 'Glassmorphism, Neumorphism & Cyberpunk FX',
    description: 'Push browser graphics to the bleeding edge with real-time backdrop blur, glowing neon shadows, organic blobs, and 3D card tilt effects.',
    range: [0.66, 0.74],
    accentColor: '#f43f5e',
    primaryCta: { text: 'Explore CSS Art & FX', href: '/art' },
    codeSnippet: `.glass-panel {\n  background: rgba(255, 255, 255, 0.05);\n  backdrop-filter: blur(20px);\n  border: 1px solid rgba(255, 255, 255, 0.15);\n}`,
  },
  {
    id: 'challenge-arena',
    number: '11',
    title: 'Can You Recreate This?',
    subtitle: 'Gamified Interactive Challenge Arena',
    description: 'Test your CSS skills by recreating target 3D UI designs with real-time pixel accuracy scoring across Easy, Medium, and Hard difficulty levels.',
    range: [0.74, 0.82],
    accentColor: '#eab308',
    primaryCta: { text: 'Enter Challenge Arena', href: '/challenges' },
    codeSnippet: `/* CHALLENGE #04: TARGET MATCH */\n.target-button {\n  background: linear-gradient(135deg, #f59e0b, #ef4444);\n  box-shadow: 0 0 25px rgba(245, 158, 11, 0.5);\n}`,
  },
  {
    id: 'knowledge-space',
    number: '12',
    title: 'Learn CSS by Seeing It.',
    subtitle: 'Futuristic 3D CSS Knowledge Library',
    description: 'Hover through floating 3D property cards for sticky positioning, flexbox, CSS variables, filters, container queries, and subgrid.',
    range: [0.82, 0.90],
    accentColor: '#10b981',
    primaryCta: { text: 'Open CSS Cheat Sheet', href: '/cheatsheet' },
    codeSnippet: `.sticky-element {\n  position: sticky;\n  top: 20px;\n  z-index: 100;\n}`,
  },
  {
    id: 'design-to-code',
    number: '13',
    title: 'What You Design Is What You Export.',
    subtitle: 'Synchronized Visual Design & Live Code Export',
    description: 'Tweak border-radius, shadows, gradients, or paddings on the visual 3D canvas and instantly watch production HTML & CSS code update.',
    range: [0.90, 0.96],
    accentColor: '#8b5cf6',
    primaryCta: { text: 'Export Production Code', href: '/editor' },
    codeSnippet: `<div class="studio-card">\n  <h2>CSS Studio Export</h2>\n</div>\n\n<style>\n.studio-card { padding: 32px; border-radius: 20px; }\n</style>`,
  },
  {
    id: 'final-studio',
    number: '14',
    title: 'Everything CSS. One Studio.',
    subtitle: 'Design. Experiment. Learn. Build. Export.',
    description: 'All 13 visual capabilities unite around the master CSS Core. Unlock the power of visual Web development without limitations.',
    range: [0.96, 1.0],
    accentColor: '#3b82f6',
    primaryCta: { text: 'Start Designing Now', href: '/editor', action: 'create' },
    secondaryCta: { text: 'Open Visual Builder', href: '/builder' },
    codeSnippet: `/* CSS STUDIO UNIVERSE READY */\n.studio-master {\n  status: complete;\n  capabilities: infinity;\n}`,
  },
];
